## `environment.yml`
name: agent
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pandas
  - numpy
  - pip:
      - langchain
      - langchain-ollama
      - langchain-experimental
      - ollama
      - streamlit
      - duckdb
      - watchdog
      - python-multipart
      - pytest
